/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.view;

import edunova.controller.ObradaDogadaj;
import edunova.controller.ObradaTip;
import edunova.controller.ObradaUtakmica;
import edunova.model.Dogadaj;
import edunova.model.Igrac;
import edunova.model.Klub;
import edunova.model.Tip;
import edunova.model.Utakmica;
import edunova.pomocno.EdunovaException;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;

/**
 *
 * @author Borna
 */
public class DogadajiPanel extends javax.swing.JPanel {
     
    private Utakmica utakmica;
    private ObradaUtakmica obradaUtakmica;
    private ObradaTip obradaTip;
    private Igrac domaciIgrac;
    private Igrac gostIgrac;
    private Dogadaj dogadaj;
    private ObradaDogadaj obradaDogadaj;
    
    
    /**
     * Creates new form DogadajiPanel
     */
    public DogadajiPanel() {
        initComponents();
         setName("Dogadaji");
         obradaUtakmica = new ObradaUtakmica();
         obradaDogadaj = new ObradaDogadaj();
         dpDatumUtakmice.setDate(new Date());
        dpDatumUtakmice.getMonthView().setZoomable(true);
        dpDatumUtakmice.setFormats(DateFormat.getDateInstance(DateFormat.MEDIUM));
        obradaTip = new ObradaTip();
        ucitajTip();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dpDatumUtakmice = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstUtakmice = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        pnlPodaci = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDomacin = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstGost = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbTip = new javax.swing.JComboBox<>();
        txtOpis = new javax.swing.JTextField();
        btnSpremi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        dpDatumUtakmice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpDatumUtakmiceActionPerformed(evt);
            }
        });

        lstUtakmice.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstUtakmice.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstUtakmiceValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(lstUtakmice);

        jLabel4.setText("Odaberite datum utakmice:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dpDatumUtakmice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dpDatumUtakmice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        lstDomacin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lstDomacin.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstDomacinValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstDomacin);

        lstGost.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstGostValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstGost);

        jLabel1.setText("Domacin:");

        jLabel2.setText("Gost:");

        btnSpremi.setText("Spremi");
        btnSpremi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpremiActionPerformed(evt);
            }
        });

        jLabel3.setText("Opis:");

        javax.swing.GroupLayout pnlPodaciLayout = new javax.swing.GroupLayout(pnlPodaci);
        pnlPodaci.setLayout(pnlPodaciLayout);
        pnlPodaciLayout.setHorizontalGroup(
            pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPodaciLayout.createSequentialGroup()
                .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPodaciLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbTip, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlPodaciLayout.createSequentialGroup()
                                .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPodaciLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtOpis, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))))
                    .addGroup(pnlPodaciLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnSpremi)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pnlPodaciLayout.setVerticalGroup(
            pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPodaciLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbTip, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOpis, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(pnlPodaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addComponent(btnSpremi)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlPodaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPodaci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dpDatumUtakmiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpDatumUtakmiceActionPerformed

        ucitajUtakmice();

    }//GEN-LAST:event_dpDatumUtakmiceActionPerformed

    private void lstUtakmiceValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstUtakmiceValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }

        utakmica = lstUtakmice.getSelectedValue();
        if (utakmica == null) {
            return;
        }
         ucitajDomacin(utakmica);
         ucitajGost(utakmica);
        
        

    }//GEN-LAST:event_lstUtakmiceValueChanged

    private void lstDomacinValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstDomacinValueChanged
       if (evt.getValueIsAdjusting()) {
            return;
        }

        domaciIgrac = lstDomacin.getSelectedValue();
        
        if (domaciIgrac == null) {
            return;
        }
      

    }//GEN-LAST:event_lstDomacinValueChanged

    private void btnSpremiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpremiActionPerformed
       dogadaj = new Dogadaj();
       if(domaciIgrac!=null && gostIgrac==null){
           dogadaj.setIgrac(domaciIgrac);
           
           
       }
       if(gostIgrac!=null && domaciIgrac==null){
           dogadaj.setIgrac(gostIgrac);
          
       }
       dogadaj.setUtakmica(utakmica);
           dogadaj.setTip(cmbTip.getItemAt(cmbTip.getSelectedIndex()));
           dogadaj.setOpis(txtOpis.getText());
           try {
               obradaDogadaj.dodaj(dogadaj);
           } catch (EdunovaException ex) {
               ex.printStackTrace();
           }
        
    }//GEN-LAST:event_btnSpremiActionPerformed

    private void lstGostValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstGostValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }

        gostIgrac = lstGost.getSelectedValue();
        
        if (gostIgrac == null) {
            return;
        }
    }//GEN-LAST:event_lstGostValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpremi;
    private javax.swing.JComboBox<Tip> cmbTip;
    private org.jdesktop.swingx.JXDatePicker dpDatumUtakmice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<Igrac> lstDomacin;
    private javax.swing.JList<Igrac> lstGost;
    private javax.swing.JList<Utakmica> lstUtakmice;
    private javax.swing.JPanel pnlPodaci;
    private javax.swing.JTextField txtOpis;
    // End of variables declaration//GEN-END:variables

private void ucitajUtakmice() {

        DefaultListModel<Utakmica> m = new DefaultListModel<>();
        SimpleDateFormat sd = new SimpleDateFormat("YYYY-MM-dd");
        
        
        obradaUtakmica.getEntiteti(sd.format(dpDatumUtakmice.getDate())).forEach((s) -> {
            m.addElement(s);
        });
        lstUtakmice.setModel(m);
    }

private void ucitajDomacin(Utakmica utakmica){
    
    DefaultListModel<Igrac> m = new DefaultListModel<>();
        SimpleDateFormat sd = new SimpleDateFormat("YYYY-MM-dd");
         
            utakmica.getDomacin().getIgraci().forEach((igrac) -> {
                m.addElement(igrac);
            });
            lstDomacin.setModel(m);
            
        
}

private void ucitajGost(Utakmica utakmica){
    DefaultListModel<Igrac> m = new DefaultListModel<>();
        SimpleDateFormat sd = new SimpleDateFormat("YYYY-MM-dd");
         
            utakmica.getGost().getIgraci().forEach((igrac) -> {
                m.addElement(igrac);
            });
            lstGost.setModel(m);
}

private void ucitajTip() {
        DefaultComboBoxModel<Tip> model = new DefaultComboBoxModel<>();
        obradaTip.getEntiteti().forEach((s) -> {
            model.addElement(s);
        });
        cmbTip.setModel(model);
    }
 
        

}
