/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edunova.view;

import edunova.controller.ObradaDogadaj;
import edunova.controller.ObradaIgrac;
import edunova.controller.ObradaTip;
import edunova.controller.ObradaUtakmica;
import edunova.model.Dogadaj;
import edunova.model.Igrac;
import edunova.model.Tip;
import edunova.model.Utakmica;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;


/**
 *
 * @author Borna
 */
public class RezultatPanel extends javax.swing.JPanel {

    
    private Utakmica utakmica;
    private ObradaUtakmica obradaUtakmica;
    private ObradaDogadaj obradaDogadaj;
    private List<List<Dogadaj>> listaDogadaja;
    private Dogadaj dogadaj;
    private Igrac igrac;
    private Tip tip;
    private ObradaIgrac  obradaIgrac;
    private ObradaTip obradaTip;
    /**
     * Creates new form RezultatPanel
     */
    public RezultatPanel() {
        initComponents();
        setName("Rezultati");
        obradaUtakmica = new ObradaUtakmica();
        obradaIgrac = new ObradaIgrac();
        obradaTip = new ObradaTip();
        dpDatumUtakmice1.setDate(new Date());
        dpDatumUtakmice1.getMonthView().setZoomable(true);
        dpDatumUtakmice1.setFormats(DateFormat.getDateInstance(DateFormat.MEDIUM));
        obradaDogadaj = new ObradaDogadaj();
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUtakmice1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dpDatumUtakmice1 = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstUtakmice1 = new javax.swing.JList<>();
        lblDomacin = new javax.swing.JLabel();
        lblGost = new javax.swing.JLabel();
        lblGolDomacina = new javax.swing.JLabel();
        lblGolGosti = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDogadaji = new javax.swing.JList<>();

        jLabel2.setText("Odaberite datum utakmice:");

        dpDatumUtakmice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpDatumUtakmice1ActionPerformed(evt);
            }
        });

        lstUtakmice1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstUtakmice1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstUtakmice1ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstUtakmice1);

        javax.swing.GroupLayout pnlUtakmice1Layout = new javax.swing.GroupLayout(pnlUtakmice1);
        pnlUtakmice1.setLayout(pnlUtakmice1Layout);
        pnlUtakmice1Layout.setHorizontalGroup(
            pnlUtakmice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUtakmice1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUtakmice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dpDatumUtakmice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUtakmice1Layout.setVerticalGroup(
            pnlUtakmice1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUtakmice1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dpDatumUtakmice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel3.setText("Rezultat:");

        jLabel1.setText("Domacin:");

        jLabel4.setText("Gost:");

        lstDogadaji.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstDogadajiValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstDogadaji);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlUtakmice1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblGolDomacina)
                                        .addComponent(lblDomacin)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblGolGosti)
                                            .addComponent(lblGost))))))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUtakmice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGost)
                    .addComponent(lblDomacin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGolGosti)
                    .addComponent(lblGolDomacina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dpDatumUtakmice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpDatumUtakmice1ActionPerformed

        ucitajUtakmice();
        

    }//GEN-LAST:event_dpDatumUtakmice1ActionPerformed

    private void lstUtakmice1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstUtakmice1ValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }

        utakmica = lstUtakmice1.getSelectedValue();
        if (utakmica == null) {
            return;
        }
        lblDomacin.setText(utakmica.getDomacin().getNaziv());
        
        
     
        lblGost.setText(utakmica.getGost().getNaziv());
        
        for (Igrac igrac : utakmica.getDomacin().getIgraci()) {
            
           if(!(obradaDogadaj.getBrojGolova(utakmica.getSifra().toString(),igrac.getSifra().toString() , "9").isEmpty())){
             lblGolDomacina.setText(String.valueOf(obradaDogadaj.getBrojGolova(utakmica.getSifra().toString(),igrac.getSifra().toString() , "9").size()));
          }else{
               lblGolDomacina.setText("0");
           }
        }
        
        
        for (Igrac igrac : utakmica.getGost().getIgraci()) {
            
           if(!(obradaDogadaj.getBrojGolova(utakmica.getSifra().toString(),igrac.getSifra().toString() , "9").isEmpty())){
             lblGolGosti.setText(String.valueOf(obradaDogadaj.getBrojGolova(utakmica.getSifra().toString(),igrac.getSifra().toString() , "9").size()));
          }else{
               lblGolGosti.setText("0");
           }
        }
        
        
        
      if  (utakmica.getDogadaji() != null) {

            DefaultListModel<Dogadaj> m2 = new DefaultListModel<>();
            utakmica.getDogadaji().forEach((d) -> {
                // System.out.println( s + " - " + s.hashCode());
                m2.addElement(d);
            });
            lstDogadaji.setModel(m2);
            lstDogadaji.repaint();
            lstDogadaji.revalidate();

        }
        
            
         
            
       
        
        
       
        

    }//GEN-LAST:event_lstUtakmice1ValueChanged

    private void lstDogadajiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstDogadajiValueChanged
    
    }//GEN-LAST:event_lstDogadajiValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker dpDatumUtakmice1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDomacin;
    private javax.swing.JLabel lblGolDomacina;
    private javax.swing.JLabel lblGolGosti;
    private javax.swing.JLabel lblGost;
    private javax.swing.JList<Dogadaj> lstDogadaji;
    private javax.swing.JList<Utakmica> lstUtakmice1;
    private javax.swing.JPanel pnlUtakmice1;
    // End of variables declaration//GEN-END:variables

    
  
    
    
private void ucitajUtakmice() {

        DefaultListModel<Utakmica> m = new DefaultListModel<>();
        SimpleDateFormat sd = new SimpleDateFormat("YYYY-MM-dd");
        
        
        obradaUtakmica.getEntiteti(sd.format(dpDatumUtakmice1.getDate())).forEach((s) -> {
            m.addElement(s);
        });
        lstUtakmice1.setModel(m);
    }
}
